/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.*;
import entity.*;
import java.awt.BorderLayout;
import java.awt.Component;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author KLphu
 */
public class HoaDonTaoGUI extends javax.swing.JFrame {

    /**
     * Creates new form KhachHangGUI
     */
    public HoaDonTaoGUI() {
        dshdt = new HoaDonTao_DAO();
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(true);
        docdulieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jPopupMenu1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPopupMenu1.setForeground(new java.awt.Color(178, 28, 77));
        jPopupMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPopupMenu1.setPreferredSize(new java.awt.Dimension(170, 250));

        jMenuItem1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\khachhang.png"));
        jMenuItem1.setText("Khách hàng");
        jMenuItem1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\hoadon.png"));
        jMenuItem2.setText("Hóa đơn");
        jMenuItem2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\bannho.png"));
        jMenuItem3.setText("Bàn");
        jMenuItem3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\thucdon.png"));
        jMenuItem4.setText("Món ăn");
        jMenuItem4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\makhuyenmai.png"));
        jMenuItem5.setText("Mã khuyến mãi");
        jMenuItem5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\doanhthu.png"));
        jMenuItem6.setText("Kết ca");
        jMenuItem6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\dangxuat.png"));
        jMenuItem7.setText("Đăng xuất");
        jMenuItem7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(178, 28, 77));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(178, 28, 77));
        jButton1.setText("Hóa đơn xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 32, 200, 45));

        jButton2.setBackground(new java.awt.Color(178, 28, 77));
        jButton2.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\menu.png"));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 10, -1, -1));

        jLabel6.setBackground(new java.awt.Color(178, 28, 77));
        jLabel6.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\user.png"));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, -1, -1));

        jLabel7.setBackground(new java.awt.Color(178, 28, 77));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TaiKhoan_DAO tk = new TaiKhoan_DAO();
        String a = tk.getname();
        jLabel7.setText(a);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 30, -1, -1));

        jButton7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(178, 28, 77));
        jButton7.setText("Hóa đơn tạo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 32, 200, 45));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(0, 168, 17));
        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Thanh toán");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\tim.png"));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 140, -1, -1));

        jTextField1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 140, 340, 36));

        jTable1.setModel(jTableModel1 = new javax.swing.table.DefaultTableModel(
            new String [] {
                "STT", "Mã hóa đơn", "Ngày lập hóa đơn", "Tên khách hàng", "Tên nhân viên", "Mã bàn", "Tổng tiền"
            }
            , 0));
    jScrollPane1.setViewportView(jTable1);

    jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 1350, -1));

    jButton8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
    jButton8.setText("Tìm");
    jButton8.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton8ActionPerformed(evt);
        }
    });
    jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 140, 70, 40));

    jDesktopPane1.add(jPanel3);
    jPanel3.setBounds(0, 0, 1490, 730);

    jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 78, 1490, 730));

    jButton6.setBackground(new java.awt.Color(178, 28, 77));
    jButton6.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\trangchu.png"));
    jButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 13, -1, -1));

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPopupMenu1.show(this, jButton2.getX()-88, jButton2.getY()+98);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HoaDonXuatGUI hoadonxuatgui = new HoaDonXuatGUI();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(hoadonxuatgui);
        hoadonxuatgui.setVisible(true);
        hoadonxuatgui.setSize(jDesktopPane1.getSize()); // Đảm bảo kích thước của JInternalFrame phù hợp với jDesktopPane1
      
        jPanel3.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.add(jPanel3);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();

        // Mở cửa sổ mới
        KhachHangGUI khachhanggui = new KhachHangGUI();
        khachhanggui.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();

        // Mở cửa sổ mới
        HoaDonTaoGUI hoadontaogui = new HoaDonTaoGUI();
        hoadontaogui.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();

        // Mở cửa sổ mới
        BanGUI bangui = new BanGUI();
        bangui.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        this.dispose();

        // Mở cửa sổ mới
        MonAnGUI monangui = new MonAnGUI();
        monangui.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.dispose();

        // Mở cửa sổ mới
        KhuyenMaiGUI khuyenmaigui = new KhuyenMaiGUI();
        khuyenmaigui.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        this.dispose();

        // Mở cửa sổ mới
        KetCaGUI ketcagui = new KetCaGUI();
        ketcagui.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TaiKhoan_DAO tk = new TaiKhoan_DAO();
        tk.fillZero();
        // Mở cửa sổ mới
        DangNhapGUI dangnhapgui = new DangNhapGUI();
        dangnhapgui.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Ban_DAO banDAO=new Ban_DAO();
        List<Ban> listAllBan=banDAO.getall();
        // Mở cửa sổ mới
        TrangChuGUI trangchugui = new TrangChuGUI(listAllBan, "");
        trangchugui.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        int r = jTable1.getSelectedRow();
        if (r > 0){
            String mahd = jTableModel1.getValueAt(r, 1).toString();
            // Mở cửa sổ mới
            ThanhToanGUI thanhtoangui = new ThanhToanGUI(mahd, "");
            thanhtoangui.setVisible(true);
        }
        else 
            JOptionPane.showMessageDialog(this, "Chọn hóa đơn cần thanh toán!!!");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        for (int i = jTableModel1.getRowCount() - 1; i >= 0; i--) {
            jTableModel1.removeRow(i);
        }
        String sdt = jTextField1.getText();
        if (sdt.isEmpty()) docdulieu();
        HoaDonTao_DAO ds = new HoaDonTao_DAO();
        List<HoaDon> list = ds.fin(sdt);
        count = 0;
        for (HoaDon s : list)
        {
            count++;
            SimpleDateFormat fm = new SimpleDateFormat("dd/MM/yyyy");
            DecimalFormat dfm = new DecimalFormat("#,###đ");
            int ttien = tongtien(s);
            String tt;
            if (ttien == 0) tt = "";
            else tt = ""+dfm.format(ttien);
            if (s.getNgayXuat() == null) continue;
            String [] r = {"" + count, s.getMaHoaDon(),fm.format(s.getNgayXuat()), s.getMaKH().getMaKH(), s.getMaNV().getMaNV(), s.getMaBan().getMaBan(), ""+ tt};
            jTableModel1.addRow(r);
        }
        jTable1.setModel(jTableModel1);
    }//GEN-LAST:event_jButton8ActionPerformed
    private void docdulieu(){
        HoaDonTao_DAO ds = new HoaDonTao_DAO();
        List<HoaDon> list = ds.getall();
        count = 0;
        for (HoaDon s : list)
        {
            count++;
            SimpleDateFormat fm = new SimpleDateFormat("dd/MM/yyyy");
            DecimalFormat dfm = new DecimalFormat("#,###đ");
            int ttien = tongtien(s); 
            String tt;
            if (ttien == 0) tt = "";
            else tt = ""+dfm.format(ttien);
            String [] r = {"" + count, s.getMaHoaDon(),fm.format(s.getNgayLap()), s.getMaKH().getMaKH(), s.getMaNV().getMaNV(), s.getMaBan().getMaBan(), ""+ tt};
            jTableModel1.addRow(r);
        }  
        jTable1.setModel(jTableModel1);
    }
    public int tongtien(HoaDon s){
        int t = 0;
        for (MonAn ma : s.getMaMonAn())
        {
            int km = ma.getGiaTien()*ma.getKhuyenMai();
            //System.out.println(km);
            int c = ma.getGiaTien() - km/100;
            //System.out.println(c);
            t += c;
        }
        //System.out.println("tongtien MonAn: "+t);
        for (KhuyenMai km : s.getMaKhuyenMai())
        {
            int c = t*km.getGiaTri();
            c /= 100;
            //System.out.println("km: "+c);
            t -= c;
        }
        int thue = t*s.getThueVAT();
        thue /= 100;
        t += thue;
        return t;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonTaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonTaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonTaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonTaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonTaoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.table.DefaultTableModel jTableModel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    private HoaDonTao_DAO dshdt;
    private int count = 0;
}
