/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import dao.*;
import entity.*;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author KLphu
 */
public class ThanhToanGUI extends javax.swing.JFrame {
    private int tongtienma = 0;
    private String maHD;
    private int[] tphieu = new int[10];
    private String makm ;
    /**
     * Creates new form KhachHangGUI
     */
    public ThanhToanGUI(String maHD, String km) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(true);
        this.maHD = maHD;
        this.makm = km;
        docdulieu(maHD);
        setthongtin(maHD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField26 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jPopupMenu1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPopupMenu1.setForeground(new java.awt.Color(178, 28, 77));
        jPopupMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPopupMenu1.setPreferredSize(new java.awt.Dimension(170, 250));

        jMenuItem1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\khachhang.png"));
        jMenuItem1.setText("Khách hàng");
        jMenuItem1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\hoadon.png"));
        jMenuItem2.setText("Hóa đơn");
        jMenuItem2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\bannho.png"));
        jMenuItem3.setText("Bàn");
        jMenuItem3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\thucdon.png"));
        jMenuItem4.setText("Món ăn");
        jMenuItem4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\makhuyenmai.png"));
        jMenuItem5.setText("Mã khuyến mãi");
        jMenuItem5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\doanhthu.png"));
        jMenuItem6.setText("Kết ca");
        jMenuItem6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\dangxuat.png"));
        jMenuItem7.setText("Đăng xuất");
        jMenuItem7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(178, 28, 77));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(178, 28, 77));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable1.setModel(jTableModel1 = new javax.swing.table.DefaultTableModel(
            new String [] {
                "STT", "Tên món", "Số lượng","Kích thước","Tổng tiền"
            }
            , 0));
    jScrollPane1.setViewportView(jTable1);

    jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 600, 680));

    jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 660, 730));

    jPanel4.setBackground(new java.awt.Color(255, 255, 255));
    jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(178, 28, 77));
    jLabel5.setText("Bàn 0");
    jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

    jLabel1.setBackground(new java.awt.Color(255, 255, 255));
    jLabel1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(178, 28, 77));
    jLabel1.setText("Tên khách hàng:");
    jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

    jTextField1.setEditable(false);
    jTextField1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jTextField1.setForeground(new java.awt.Color(178, 28, 77));
    jTextField1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField1ActionPerformed(evt);
        }
    });
    jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 47, 210, -1));

    jLabel2.setBackground(new java.awt.Color(255, 255, 255));
    jLabel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(178, 28, 77));
    jLabel2.setText("Tên nhân viên:");
    jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

    jTextField2.setEditable(false);
    jTextField2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jTextField2.setForeground(new java.awt.Color(178, 28, 77));
    jTextField2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField2ActionPerformed(evt);
        }
    });
    jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 210, -1));

    jLabel3.setBackground(new java.awt.Color(255, 255, 255));
    jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(178, 28, 77));
    jLabel3.setText("Tổng cộng:");
    jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

    jTextField3.setEditable(false);
    jTextField3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jTextField3.setForeground(new java.awt.Color(178, 28, 77));
    jTextField3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField3ActionPerformed(evt);
        }
    });
    jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 210, -1));

    jLabel4.setBackground(new java.awt.Color(255, 255, 255));
    jLabel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(178, 28, 77));
    jLabel4.setText("Mã khuyến mãi:");
    jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

    jTextField4.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jTextField4.setForeground(new java.awt.Color(178, 28, 77));
    jTextField4.setText("0");
    jTextField4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField4ActionPerformed(evt);
        }
    });
    jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 180, -1));

    jLabel8.setBackground(new java.awt.Color(255, 255, 255));
    jLabel8.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(178, 28, 77));
    jLabel8.setText("10%");
    jLabel8.setToolTipText("");
    jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

    jLabel9.setBackground(new java.awt.Color(255, 255, 255));
    jLabel9.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(178, 28, 77));
    jLabel9.setText("Thành tiền:");
    jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

    jTextField6.setEditable(false);
    jTextField6.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jTextField6.setForeground(new java.awt.Color(178, 28, 77));
    jTextField6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField6ActionPerformed(evt);
        }
    });
    jPanel4.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 210, -1));

    jLabel10.setBackground(new java.awt.Color(255, 255, 255));
    jLabel10.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
    jLabel10.setForeground(new java.awt.Color(178, 28, 77));
    jLabel10.setText("Tiền khách đưa:");
    jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

    jTextField7.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jTextField8.setEditable(false);
    jTextField7.setForeground(new java.awt.Color(178, 28, 77));
    jTextField7.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField7ActionPerformed(evt);
        }
    });
    jPanel4.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 210, -1));

    jLabel11.setBackground(new java.awt.Color(255, 255, 255));
    jLabel11.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
    jLabel11.setForeground(new java.awt.Color(178, 28, 77));
    jLabel11.setText("Trả lại khách:");
    jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

    jTextField8.setEditable(false);
    jTextField8.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jTextField8.setForeground(new java.awt.Color(178, 28, 77));
    jTextField8.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField8ActionPerformed(evt);
        }
    });
    jPanel4.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 210, -1));

    jLabel12.setBackground(new java.awt.Color(255, 255, 255));
    jLabel12.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
    jLabel12.setForeground(new java.awt.Color(178, 28, 77));
    jLabel12.setText("VAT:");
    jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

    jButton5.setBackground(new java.awt.Color(0, 168, 17));
    jButton5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
    jButton5.setForeground(new java.awt.Color(255, 255, 255));
    jButton5.setText("Xác nhận");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });
    jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 190, 40));

    jButton4.setBackground(new java.awt.Color(9, 69, 224));
    jButton4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
    jButton4.setForeground(new java.awt.Color(255, 255, 255));
    jButton4.setText("Lưu & xuất");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });
    jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, 190, 40));

    jButton7.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jButton7.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\themkh.png"));
    jButton7.setPreferredSize(new java.awt.Dimension(24, 24));
    jButton7.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton7ActionPerformed(evt);
        }
    });
    jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 30, 30));

    jTextField26.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jTextField26.setForeground(new java.awt.Color(178, 28, 77));
    jTextField26.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField26ActionPerformed(evt);
        }
    });
    jPanel4.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 180, -1));

    jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 440, 730));

    jPanel5.setBackground(new java.awt.Color(255, 255, 255));
    jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel37.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
    jLabel37.setForeground(new java.awt.Color(178, 28, 77));
    jLabel37.setText("Tiền Thừa");
    jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

    jLabel13.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jLabel13.setForeground(new java.awt.Color(178, 28, 77));
    jLabel13.setText("500.000");
    jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

    jLabel14.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jLabel14.setForeground(new java.awt.Color(178, 28, 77));
    jLabel14.setText("200.000");
    jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

    jLabel15.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jLabel15.setForeground(new java.awt.Color(178, 28, 77));
    jLabel15.setText("100.000");
    jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

    jLabel16.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jLabel16.setForeground(new java.awt.Color(178, 28, 77));
    jLabel16.setText("50.000");
    jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

    jLabel23.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jLabel23.setForeground(new java.awt.Color(178, 28, 77));
    jLabel23.setText("20.000");
    jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

    jLabel19.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jLabel19.setForeground(new java.awt.Color(178, 28, 77));
    jLabel19.setText("10.000");
    jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

    jLabel29.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jLabel29.setForeground(new java.awt.Color(178, 28, 77));
    jLabel29.setText("5.000");
    jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

    jLabel25.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jLabel25.setForeground(new java.awt.Color(178, 28, 77));
    jLabel25.setText("2.000");
    jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

    jLabel35.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jLabel35.setForeground(new java.awt.Color(178, 28, 77));
    jLabel35.setText("1.000");
    jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

    jLabel38.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
    jLabel38.setForeground(new java.awt.Color(178, 28, 77));
    jLabel38.setText("Mệnh giá");
    jPanel5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

    jLabel39.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
    jLabel39.setForeground(new java.awt.Color(178, 28, 77));
    jLabel39.setText("Khách trả");
    jPanel5.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

    jTextField5.setForeground(new java.awt.Color(178, 28, 77));
    jTextField5.setText("0");
    jTextField5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField5ActionPerformed(evt);
        }
    });
    jPanel5.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

    jTextField9.setForeground(new java.awt.Color(178, 28, 77));
    jTextField9.setText("0");
    jTextField9.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField9ActionPerformed(evt);
        }
    });
    jPanel5.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

    jTextField10.setForeground(new java.awt.Color(178, 28, 77));
    jTextField10.setText("0");
    jTextField10.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField10ActionPerformed(evt);
        }
    });
    jPanel5.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

    jTextField11.setForeground(new java.awt.Color(178, 28, 77));
    jTextField11.setText("0");
    jTextField11.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField11ActionPerformed(evt);
        }
    });
    jPanel5.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

    jTextField12.setForeground(new java.awt.Color(178, 28, 77));
    jTextField12.setText("0");
    jTextField12.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField12ActionPerformed(evt);
        }
    });
    jPanel5.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

    jTextField13.setForeground(new java.awt.Color(178, 28, 77));
    jTextField13.setText("0");
    jTextField13.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField13ActionPerformed(evt);
        }
    });
    jPanel5.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

    jTextField14.setForeground(new java.awt.Color(178, 28, 77));
    jTextField14.setText("0");
    jTextField14.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField14ActionPerformed(evt);
        }
    });
    jPanel5.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

    jTextField15.setForeground(new java.awt.Color(178, 28, 77));
    jTextField15.setText("0");
    jTextField15.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField15ActionPerformed(evt);
        }
    });
    jPanel5.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, -1, -1));

    jTextField16.setForeground(new java.awt.Color(178, 28, 77));
    jTextField16.setText("0");
    jTextField16.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField16ActionPerformed(evt);
        }
    });
    jPanel5.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

    jTextField17.setForeground(new java.awt.Color(178, 28, 77));
    jTextField17.setText("0");
    jTextField17.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField17ActionPerformed(evt);
        }
    });
    jPanel5.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

    jTextField18.setForeground(new java.awt.Color(178, 28, 77));
    jTextField18.setText("0");
    jTextField18.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField18ActionPerformed(evt);
        }
    });
    jPanel5.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

    jTextField19.setForeground(new java.awt.Color(178, 28, 77));
    jTextField19.setText("0");
    jTextField19.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField19ActionPerformed(evt);
        }
    });
    jPanel5.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

    jTextField20.setForeground(new java.awt.Color(178, 28, 77));
    jTextField20.setText("0");
    jTextField20.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField20ActionPerformed(evt);
        }
    });
    jPanel5.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

    jTextField21.setForeground(new java.awt.Color(178, 28, 77));
    jTextField21.setText("0");
    jTextField21.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField21ActionPerformed(evt);
        }
    });
    jPanel5.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

    jTextField22.setForeground(new java.awt.Color(178, 28, 77));
    jTextField22.setText("0");
    jTextField22.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField22ActionPerformed(evt);
        }
    });
    jPanel5.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

    jTextField23.setForeground(new java.awt.Color(178, 28, 77));
    jTextField23.setText("0");
    jTextField23.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField23ActionPerformed(evt);
        }
    });
    jPanel5.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

    jTextField24.setForeground(new java.awt.Color(178, 28, 77));
    jTextField24.setText("0");
    jTextField24.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField24ActionPerformed(evt);
        }
    });
    jPanel5.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

    jTextField25.setForeground(new java.awt.Color(178, 28, 77));
    jTextField25.setText("0");
    jTextField25.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField25ActionPerformed(evt);
        }
    });
    jPanel5.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

    jButton13.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
    jButton13.setForeground(new java.awt.Color(178, 28, 77));
    jButton13.setText("Clear All");
    jButton13.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton13ActionPerformed(evt);
        }
    });
    jPanel5.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, -1, 30));

    jLabel17.setBackground(new java.awt.Color(255, 255, 255));
    jLabel17.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
    jLabel17.setForeground(new java.awt.Color(178, 28, 77));
    jLabel17.setText("0");
    jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 120, 30));

    jButton14.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
    jButton14.setForeground(new java.awt.Color(178, 28, 77));
    jButton14.setText("Chuyển Khoản:");
    jButton14.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton14ActionPerformed(evt);
        }
    });
    jPanel5.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, 30));

    jButton15.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
    jButton15.setForeground(new java.awt.Color(178, 28, 77));
    jButton15.setText("Tính");
    jButton15.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton15ActionPerformed(evt);
        }
    });
    jPanel5.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 70, 30));

    jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 320, 730));

    jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 1510, 760));

    jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
    jButton1.setForeground(new java.awt.Color(178, 28, 77));
    jButton1.setText("Thanh toán");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 200, 45));

    jButton2.setBackground(new java.awt.Color(178, 28, 77));
    jButton2.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\menu.png"));
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 10, -1, -1));

    jButton6.setBackground(new java.awt.Color(178, 28, 77));
    jButton6.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\trangchu.png"));
    jButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 13, -1, -1));

    jLabel6.setBackground(new java.awt.Color(178, 28, 77));
    jLabel6.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\user.png"));
    jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, -1, -1));

    jLabel7.setBackground(new java.awt.Color(178, 28, 77));
    jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    TaiKhoan_DAO tk = new TaiKhoan_DAO();
    String a = tk.getname();
    jLabel7.setText(a);
    jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 30, -1, -1));

    getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);
    jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPopupMenu1.show(this, jButton2.getX()-88, jButton2.getY()+98);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();

        // Mở cửa sổ mới
        KhachHangGUI khachhanggui = new KhachHangGUI();
        khachhanggui.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();

        // Mở cửa sổ mới
        HoaDonTaoGUI hoadontaogui = new HoaDonTaoGUI();
        hoadontaogui.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();

        // Mở cửa sổ mới
        BanGUI bangui = new BanGUI();
        bangui.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        this.dispose();

        // Mở cửa sổ mới
        MonAnGUI monangui = new MonAnGUI();
        monangui.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.dispose();

        // Mở cửa sổ mới
        KhuyenMaiGUI khuyenmaigui = new KhuyenMaiGUI();
        khuyenmaigui.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        this.dispose();

        // Mở cửa sổ mới
        KetCaGUI ketcagui = new KetCaGUI();
        ketcagui.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TaiKhoan_DAO tk = new TaiKhoan_DAO();
        tk.fillZero();
        // Mở cửa sổ mới
        DangNhapGUI dangnhapgui = new DangNhapGUI();
        dangnhapgui.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Ban_DAO banDAO=new Ban_DAO();
        List<Ban> listAllBan=banDAO.getall();
        // Mở cửa sổ mới
        TrangChuGUI trangchugui = new TrangChuGUI(listAllBan, "");
        trangchugui.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Date d = new Date();
        int day = 0;
        String dd = "";
        day = d.getDate();
        if (day < 10)
            dd = "0"+day;
        else dd = day + "";
        int month;
        String mm = "";
        month = d.getMonth()+1;
        if (month < 10)
            mm = "0"+month;
        else mm = month + "";
        int year;
        String yy = "";
        year = d.getYear()-100;
        if (year < 10)
            yy = "0"+year;
        else yy = year + "";
        String mphiu = "P"+dd+mm+yy;
        int tck = Integer.parseInt(jLabel17.getText());
        ThanhToan_Dao tt = new ThanhToan_Dao();
        Phieu p = new Phieu(mphiu, maHD, d, tphieu[0], tphieu[1], tphieu[2], tphieu[3], 
                tphieu[4], tphieu[5], tphieu[6], tphieu[7], tphieu[8], tck);
        if (tt.crephieu(p)) {
            Ban_DAO b = new Ban_DAO();
            b.upd("Trống", b.getmathd(maHD));
            tt.upd(d, maHD);
            JOptionPane.showMessageDialog(this, "Lưu thành công");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        HoadonGUI hoadongui = new HoadonGUI();
        hoadongui.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int t = Integer.parseInt(jTextField6.getText());
        FormThemKhuyenMai formthemkm = new FormThemKhuyenMai(maHD, t);
        formthemkm.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jTextField25.setText("0");
        jTextField24.setText("0");
        jTextField23.setText("0");
        jTextField22.setText("0");
        jTextField21.setText("0");
        jTextField20.setText("0");
        jTextField19.setText("0");
        jTextField18.setText("0");
        jTextField17.setText("0");
        jTextField11.setText("0");
        jTextField10.setText("0");
        jTextField9.setText("0");
        jTextField5.setText("0");
        jTextField12.setText("0");
        jTextField13.setText("0");
        jTextField14.setText("0");
        jTextField16.setText("0");
        jTextField15.setText("0");
        jTextField7.setText("");
        jTextField8.setText("");
        jLabel17.setText("0");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        String thanhTien = jTextField6.getText();
        jTextField7.setText(thanhTien+"");
        jTextField8.setText("0");
        jLabel17.setText(thanhTien+"");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        int tong = Integer.parseInt(jTextField6.getText());
        int t500 = Integer.parseInt(jTextField11.getText());//11
        int t200 = Integer.parseInt(jTextField10.getText());//10
        int t100 = Integer.parseInt(jTextField9.getText());//9
        int t50 = Integer.parseInt(jTextField5.getText());//5
        int t20 = Integer.parseInt(jTextField12.getText());//2
        int t10 = Integer.parseInt(jTextField13.getText());//3
        int t5 = Integer.parseInt(jTextField14.getText());//4
        int t2 = Integer.parseInt(jTextField16.getText());//16
        int t1 = Integer.parseInt(jTextField15.getText());//15
        tphieu[0] = t1; tphieu[1] = t2; tphieu[2] = t5; tphieu[3] = t10; tphieu[4] = t20; 
        tphieu[5] = t50; tphieu[6] = t100; tphieu[7] = t200; tphieu[8] = t500; 
        int tkhach = t500*500000+t200*200000+t100*100000+t50*50000+t20*20000+t10*10000
                    +t5*5000+t2*2000+t1*1000;
        jTextField7.setText(tkhach+"");
        int tthoi = tkhach-tong;
        jTextField8.setText(tthoi+"");
        
        int tam = tthoi;
        int[] tien = {1000, 2000, 5000, 10000, 20000, 
                      50000, 100000, 200000, 500000};
        int i = 8;
        while (i > 0 || tam > 0){
            if (tam - tien[i] >= 0){
                tphieu[i]--;
                tam-=tien[i];
            }
            else {
                i--;
            }
        }
        int tt500 = t500-tphieu[8], tt200 = t200-tphieu[7], tt100 = t100-tphieu[6], 
            tt50 = t50-tphieu[5], tt20 = t20-tphieu[4], tt10 = t10-tphieu[3], 
            tt5 = t5-tphieu[2], tt2 = t2-tphieu[1], tt1 = t1-tphieu[0];
        jTextField25.setText(tt500+"");
        jTextField24.setText(tt200+"");
        jTextField23.setText(tt100+"");
        jTextField22.setText(tt50+"");
        jTextField21.setText(tt20+"");
        jTextField20.setText(tt10+"");
        jTextField19.setText(tt5+"");
        jTextField18.setText(tt2+"");
        jTextField17.setText(tt1+"");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed
    
    private void docdulieu(String mahd){
        ThanhToan_Dao ds = new ThanhToan_Dao();
        List<MonAn> list = ds.getall(mahd);
        count = 0;
        for (MonAn ma : list)
        {
            SimpleDateFormat fm = new SimpleDateFormat("dd/MM/yyyy");
            DecimalFormat dfm = new DecimalFormat("#,###đ");
            count++;
            String Ten = ma.getTenMonAn();
            String size = ma.getSize();
            int sl = ma.getsl();
            int km = ma.getGiaTien()*ma.getKhuyenMai();
            int c = (ma.getGiaTien() - km/100)*sl;
            sl = ma.getsl();
            tongtienma += c;
            String [] r = {"" + count, Ten, sl+"", size, c+""};
            jTableModel1.addRow(r);
        }
        jTable1.setModel(jTableModel1);
    }
    
    private void setthongtin(String mahd){
        ThanhToan_Dao tt = new ThanhToan_Dao();
        String tenkh = tt.gettenkh(mahd);
        jTextField1.setText(tenkh);
        String tenNV = tt.gettennv(mahd);
        jTextField2.setText(tenNV);
        jTextField3.setText(tongtienma+"");
        
        KhuyenMai_DAO kmd = new KhuyenMai_DAO();
        int tkm = kmd.getvalue(makm);
        jTextField4.setText(tkm+"");
        jTextField26.setText(makm);
        int km = tt.getkm(makm);
        int c = tongtienma*km;
        int tientruocthue = tongtienma - c/100 ;
        int thue = tientruocthue*10;
        int thanhtien = tientruocthue + thue/100;
        int lamtron = thanhtien % 1000;
        thanhtien -= lamtron;
        if (lamtron >= 500)
            thanhtien += 1000; 
        jTextField6.setText(thanhtien+"");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThanhToanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThanhToanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThanhToanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThanhToanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThanhToanGUI("", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.table.DefaultTableModel jTableModel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
    private ThanhToan_Dao dsma;
    private int count = 0;
}
