/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JPanel;
import dao.*;
import entity.*;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.plaf.SpinnerUI;
/**
 *
 * @author KLphu
 */
public class TrangChuGUI extends javax.swing.JFrame {
    private Ban_DAO banDAO = new Ban_DAO();
    private List<MonAn> list = new ArrayList<MonAn>();
    private String mahd = "";
    private long tongtienHD = 0;
    private int sizelistma = 0, zzz = 0;
    /**
     * Creates new form KhachHangGUI
     */
    public TrangChuGUI(List<Ban> list, String sdt) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        if (sdt.equals("")) jLabel13.setText("Khách Hàng");
        else jLabel13.setText(sdt);
        Ban_DAO b = new Ban_DAO();
        String chk = b.check();
        if (!chk.equals("error")) jLabel5.setText(b.getten());
        paintBan(list);
        setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPopupMenu1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPopupMenu1.setForeground(new java.awt.Color(178, 28, 77));
        jPopupMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPopupMenu1.setPreferredSize(new java.awt.Dimension(170, 250));

        jMenuItem1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\khachhang.png"));
        jMenuItem1.setText("Khách hàng");
        jMenuItem1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\hoadon.png"));
        jMenuItem2.setText("Hóa đơn");
        jMenuItem2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\bannho.png"));
        jMenuItem3.setText("Bàn");
        jMenuItem3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\thucdon.png"));
        jMenuItem4.setText("Món ăn");
        jMenuItem4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\makhuyenmai.png"));
        jMenuItem5.setText("Mã khuyến mãi");
        jMenuItem5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\doanhthu.png"));
        jMenuItem6.setText("Kết ca");
        jMenuItem6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\dangxuat.png"));
        jMenuItem7.setText("Đăng xuất");
        jMenuItem7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(178, 28, 77));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(178, 28, 77));
        jButton1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\thucdon.png"));
        jButton1.setText("Thực đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 32, 200, 45));

        jButton2.setBackground(new java.awt.Color(178, 28, 77));
        jButton2.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\menu.png"));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 10, -1, -1));

        jLabel6.setBackground(new java.awt.Color(178, 28, 77));
        jLabel6.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\user.png"));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, -1, -1));

        jLabel7.setBackground(new java.awt.Color(178, 28, 77));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TaiKhoan_DAO tk = new TaiKhoan_DAO();
        String a = tk.getname();
        jLabel7.setText(a);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 30, -1, -1));

        jButton7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(178, 28, 77));
        jButton7.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\phongban.png"));
        jButton7.setText("Phòng bàn");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 32, 200, 45));

        jTextField4.setBackground(new java.awt.Color(178, 28, 77));
        jTextField4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 35, 290, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(178, 28, 77));
        jButton3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Tất cả");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        jButton9.setBackground(new java.awt.Color(178, 28, 77));
        jButton9.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Lầu 1");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 30));

        jButton10.setBackground(new java.awt.Color(178, 28, 77));
        jButton10.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Lầu 2");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 90, 30));

        jButton11.setBackground(new java.awt.Color(178, 28, 77));
        jButton11.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Lầu 3");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 90, 30));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(jPanel5);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 740, 640));

        jButton12.setBackground(new java.awt.Color(178, 28, 77));
        jButton12.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Mang về");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 100, 30));

        jDesktopPane1.add(jPanel3);
        jPanel3.setBounds(0, 0, 760, 730);

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 78, 760, 730));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\phongban.png"));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(178, 28, 77));
        jLabel3.setText("Đơn giá");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(178, 28, 77));
        jLabel5.setText("Bàn 0");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(178, 28, 77));
        jLabel8.setText("#");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(178, 28, 77));
        jLabel9.setText("Tên thực đơn");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(178, 28, 77));
        jLabel10.setText("Thành tiền");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(178, 28, 77));
        jLabel11.setText("Số lượng");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\xoa.png"));
        jPanel7.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\note.png"));
        jLabel14.setPreferredSize(new java.awt.Dimension(24, 24));
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTextField1.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(178, 28, 77));
        jTextField1.setText("Nhập ghi chú");
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(178, 28, 77)));
        jPanel7.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 170, 30));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(178, 28, 77));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("0");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 120, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(178, 28, 77));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("0");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 20, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(178, 28, 77));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Tên thực đơn");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 160, -1));

        jSpinner1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jPanel7.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 50, 30));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(178, 28, 77));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("0");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 130, -1));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 670, 90));

        jScrollPane2.setViewportView(jPanel6);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 690, 520));

        jPanel4.setBackground(new java.awt.Color(239, 239, 239));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(9, 69, 224));
        jButton4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\luutam.png"));
        jButton4.setText("Lưu tạm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 330, 60));

        jButton5.setBackground(new java.awt.Color(0, 168, 17));
        jButton5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\thanhtoan.png"));
        jButton5.setText("Thanh toán");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 330, 60));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(":");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 11, 20, 30));

        jButton6.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\themkh.png"));
        jButton6.setPreferredSize(new java.awt.Dimension(24, 24));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 15, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Khách hàng");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, 130, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("0");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 170, 30));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("0");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 11, 20, 30));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Tổng cộng");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 11, 80, 30));

        jButton13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(178, 28, 77));
        jButton13.setText("Tách đơn");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 27, -1, -1));

        jButton14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton14.setForeground(new java.awt.Color(178, 28, 77));
        jButton14.setText("Đổi bàn");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 27, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 710, 120));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 78, 710, 730));

        jLabel2.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\tim1.png"));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPopupMenu1.show(this, jButton2.getX()-88, jButton2.getY()+98);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MonAn_DAO monAnDAO = new MonAn_DAO();
        List<MonAn> list = monAnDAO.getall();
        ThucDonGUI thucdon = new ThucDonGUI();
        jDesktopPane1.removeAll();
        jP1 = new javax.swing.JPanel();
        jP1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane3 = new javax.swing.JScrollPane();
        // Code of sub-components and layout - not shown here
        jScrollPane3.setViewportView(jP1);
        thucdon.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 740, 640));
        paintMonAn(list);
        
        jDesktopPane1.add(thucdon);
        thucdon.setVisible(true);
        thucdon.setSize(jDesktopPane1.getSize()); // Đảm bảo kích thước của JInternalFrame phù hợp với jDesktopPane1
      
        jPanel3.setVisible(false);
        
        JButton btnGaRan=  thucdon.getGaRan();
        btnGaRan.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e) {
                MonAn_DAO monAnDAO=new MonAn_DAO();
                List<MonAn> l=monAnDAO.getMonAnTheoLoai("Gà");
                System.out.println(l);
                jP1.removeAll();
                paintMonAnTungLoai(l);
                jP1.repaint();
                jP1.validate();
            }
        });
        
        JButton btnBurger=  thucdon.getBurger();
        btnBurger.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e) {
                MonAn_DAO monAnDAO=new MonAn_DAO();
                List<MonAn> l=monAnDAO.getMonAnTheoLoai("Burger"); 
                System.out.println(l);
                jP1.removeAll();
                paintMonAnTungLoai(l);
                jP1.repaint();
                jP1.validate();
            }
            
        });
        
        JButton btnCom=  thucdon.getCom();
        btnCom.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e) {
                MonAn_DAO monAnDAO=new MonAn_DAO();
                List<MonAn> l=monAnDAO.getMonAnTheoLoai("Cơm"); 
                System.out.println(l);
                jP1.removeAll();
                paintMonAnTungLoai(l);
                jP1.repaint();
                jP1.validate();
            }
        });
        
        JButton btnMy= thucdon.getMy();
        btnMy.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e) {
                MonAn_DAO monAnDAO=new MonAn_DAO();
                List<MonAn> l=monAnDAO.getMonAnTheoLoai("Mì Ý"); 
                System.out.println(l);
                jP1.removeAll();
                paintMonAnTungLoai(l);
                jP1.repaint();
                jP1.validate();
            }
        });
        
        JButton btnTrangMieng=  thucdon.getTrangMieng();
        btnTrangMieng.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e) {
                MonAn_DAO monAnDAO=new MonAn_DAO();
                List<MonAn> l=monAnDAO.getMonAnTheoLoai("THỨC UỐNG & TRÁNG MIỆNG"); 
                System.out.println(l);
                jP1.removeAll();
                paintMonAnTungLoai(l);
                jP1.repaint();
                jP1.validate();
            }
        });
        
        JButton btnCombo=  thucdon.getCombo();
        btnCombo.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e) {
                MonAn_DAO monAnDAO=new MonAn_DAO();
                List<MonAn> l=monAnDAO.getMonAnTheoLoai("Combo"); 
                System.out.println(l);
                jP1.removeAll();
                paintMonAnTungLoai(l);
                jP1.repaint();
                jP1.validate();
            }
        });
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
//
    private void paintMonAn(List<MonAn> list){
        int x=20;
        int y=20;
        int i = 0;
        int z = 0;
        for (MonAn monAn : list) {
            i++;
          JPanel jp=  paint1MonAn(monAn, i, z);
          jP1.add(jp, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, 210, 190));
        jp.setBounds(x, y, 210, 190);
          x=x+240;
          //Nhân số món ăn trên 1 hàng lên
          if(x>690){
              x=20;
              y=y+210;
          }
//          jPanel1.repaint();
//          jPanel1.validate();
        }
    }
    private JPanel paint1MonAn(MonAn ma, int i, int z){
        JPanel jP2=new JPanel();
        JPanel jP3=new JPanel();
        JButton jB6 = new JButton();
        JLabel jL1 = new javax.swing.JLabel();
        JLabel jL2 = new javax.swing.JLabel();
        
//        jP1.setLayout(null);

        jP2.setBackground(new java.awt.Color(255, 255, 255));
        jP2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(178, 28, 77), 5, true));

        jP3.setLayout(new java.awt.BorderLayout());
        
        jB6.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img_ThucDon\\"+i+".jpg"));
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //  jButton6ActionPerformed(evt);
                jPanel6.removeAll();
                boolean dk = true;
                for (MonAn e : list){
                    if (e.getMaMonAn().equals(ma.getMaMonAn())) 
                    {
                        int sll = e.getsl()+1;
                        e.setsl(sll);
                        dk = false;
                    }
                }
                {
                    if (dk) {
                        int sl = 0;
                        sl++;
                        ma.setsl(sl);
                        list.add(ma);   
                    }
                    jLabel15.setText(list.size()+"");
                    int km = ma.getGiaTien()*ma.getKhuyenMai();
                    int c = ma.getGiaTien() - km/100;
                    JPanel jp = paint1mon(1+zzz, ma.getTenMonAn(), 1, c); 
                    zzz++;
                    jPanel6.add(jp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10+sizelistma, 670, 90));
                    sizelistma+=90;
                }
            }
        });
        jP3.add(jB6, java.awt.BorderLayout.CENTER);

        jL1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jL1.setForeground(new java.awt.Color(178, 28, 77));
        jL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DecimalFormat dfm = new DecimalFormat("#,###đ");
        jL1.setText(dfm.format(ma.getGiaTien()));

        jL2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jL2.setForeground(new java.awt.Color(178, 28, 77));
        jL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL2.setText(ma.getTenMonAn());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jP2);
        jP2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jP3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

//        jPanel1.add(jPanel2);
//        jPanel2.setBounds(20, 20, 210, 190);
        jP2.setPreferredSize(new Dimension(210,190));
        return jP2;
}
//
    private void paintMonAnTungLoai(List<MonAn> list){
        int x=20;
        int y=20;
        int i = 0;
        int z = 0;
        for (MonAn monAn : list) {
            i++;
          JPanel jp=  paint1MonAnTungLoai(monAn, i, z, monAn.getSize());
          jP1.add(jp, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, 210, 190));
        jp.setBounds(x, y, 210, 190);
          x=x+240;
          //Nhân số món ăn trên 1 hàng lên
          if(x>690){
              x=20;
              y=y+210;
          }
//          jPanel1.repaint();
//          jPanel1.validate();
        }
    }
    private JPanel paint1MonAnTungLoai(MonAn ma, int i, int z, String ten){
        JPanel jP2=new JPanel();
        JPanel jP3=new JPanel();
        JButton jB6 = new JButton();
        JLabel jL1 = new javax.swing.JLabel();
        JLabel jL2 = new javax.swing.JLabel();
        
//        jP1.setLayout(null);

        jP2.setBackground(new java.awt.Color(255, 255, 255));
        jP2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(178, 28, 77), 5, true));
        String ten1 = "img_ThucDon";
        jP3.setLayout(new java.awt.BorderLayout());
        
        jB6.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\"+ten+"\\"+i+".jpg"));
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //  jButton6ActionPerformed(evt);
                jPanel6.removeAll();
                boolean dk = true;
                for (MonAn e : list){
                    if (e.getMaMonAn().equals(ma.getMaMonAn())) 
                    {
                        int sll = e.getsl()+1;
                        e.setsl(sll);
                        dk = false;
                    }
                }
                {
                    if (dk) {
                        int sl = 0;
                        sl++;
                        ma.setsl(sl);
                        list.add(ma);   
                    }
                    jLabel15.setText(list.size()+"");
                    int km = ma.getGiaTien()*ma.getKhuyenMai();
                    int c = ma.getGiaTien() - km/100;
                    JPanel jp = paint1mon(1+zzz, ma.getTenMonAn(), 1, c); 
                    zzz++;
                    jPanel6.add(jp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10+sizelistma, 670, 90));
                    sizelistma+=90;
                }
            }
        });
        jP3.add(jB6, java.awt.BorderLayout.CENTER);

        jL1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jL1.setForeground(new java.awt.Color(178, 28, 77));
        jL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DecimalFormat dfm = new DecimalFormat("#,###đ");
        jL1.setText(dfm.format(ma.getGiaTien()));

        jL2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jL2.setForeground(new java.awt.Color(178, 28, 77));
        jL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL2.setText(ma.getTenMonAn());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jP2);
        jP2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jP3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

//        jPanel1.add(jPanel2);
//        jPanel2.setBounds(20, 20, 210, 190);
        jP2.setPreferredSize(new Dimension(210,190));
        return jP2;
}
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        list = new ArrayList<MonAn>();
        mahd = "";
        tongtienHD = 0;
        sizelistma = 0;
        zzz = 0;
        jDesktopPane1.removeAll();
        jDesktopPane1.add(jPanel3);
        jPanel6.removeAll();
        jPanel3.setVisible(true);
        List<Ban> listAll=banDAO.getall();
        //System.err.println(listAll);
        jPanel5.removeAll();
        paintBan(listAll);
        jPanel5.repaint();
        jPanel5.validate();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        List<Ban> listLau1 = banDAO.getBanByLau(1);
        System.err.println(listLau1);
        jPanel5.removeAll();
        paintBan(listLau1);
        jPanel5.repaint();
        jPanel5.validate();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        List<Ban> listLau2=banDAO.getBanByLau(2);
        System.err.println(listLau2);
        jPanel5.removeAll();
        paintBan(listLau2);
        jPanel5.repaint();
        jPanel5.validate();

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        List<Ban> listLau1=banDAO.getBanByLau(3);
        System.err.println(listLau1);
        jPanel5.removeAll();
        paintBan(listLau1);
        jPanel5.repaint();
        jPanel5.validate();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (!mahd.isEmpty())
            JOptionPane.showMessageDialog(this, "Hóa đơn đã tồn tại");
        else if (list.isEmpty())
            JOptionPane.showMessageDialog(this, "Chưa thêm món ăn");
        
        if (mahd.isEmpty() && !list.isEmpty()) {
            themMon();
            Ban_DAO b = new Ban_DAO();
            b.upd("Bận", b.getma(jLabel5.getText()));
            
            Ban_DAO banDAO=new Ban_DAO();
            List<Ban> listAllBan=banDAO.getall();
        // Mở cửa sổ mới
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed
    private void themMon(){
        TaiKhoan_DAO tk = new TaiKhoan_DAO();
        TrangChu_DAO tc = new TrangChu_DAO();
        Ban_DAO b = new Ban_DAO();
        String manv = tk.getma();
        
        mahd = tc.phatsinh(manv);
        Date now = new Date();
        String makh = "";
        if (!jLabel13.getText().equals("Khách hàng")){
            makh = jLabel13.getText();
            String mab = b.getma(jLabel5.getText());
            HoaDon hd = new HoaDon(mahd, now, new KhachHang(makh), new NhanVien(manv), null, 10, null,new Ban(mab), list);
            if (tc.crehd(hd)) {
                for (MonAn e : hd.getMaMonAn()){
                    tc.crecthd(e, hd.getMaHoaDon());
                }
                JOptionPane.showMessageDialog(this, "Lưu thành công"); 
            }
        } 
        else 
            JOptionPane.showMessageDialog(this, "Chọn khách hàng!!!");
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        if (mahd.isEmpty())
            if (list.isEmpty())
                JOptionPane.showMessageDialog(this, "Chưa thêm món ăn");
            else {
                themMon();
                Ban_DAO b = new Ban_DAO();
                b.fillZero();
                ThanhToanGUI thanhtoangui = new ThanhToanGUI(mahd, "");
                thanhtoangui.setVisible(true);
            }
        else{
            ThanhToanGUI thanhtoangui = new ThanhToanGUI(mahd, "");
            thanhtoangui.setVisible(true);
        }
    
        // Mở cửa sổ mới
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        FormThemKhachHang formthemhk = new FormThemKhachHang();
        formthemhk.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    
        // Mở cửa sổ mới
        KhachHangGUI khachhanggui = new KhachHangGUI();
        khachhanggui.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        
        TaiKhoan_DAO tk = new TaiKhoan_DAO();
        tk.fillZero();
        this.dispose();
        // Mở cửa sổ mới
        DangNhapGUI dangnhapgui = new DangNhapGUI();
        dangnhapgui.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
    
        // Mở cửa sổ mới
        HoaDonTaoGUI hoadontaogui = new HoaDonTaoGUI();
        hoadontaogui.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
    
        // Mở cửa sổ mới
        BanGUI bangui = new BanGUI();
        bangui.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.dispose();
    
        // Mở cửa sổ mới
        KhuyenMaiGUI khuyenmaigui = new KhuyenMaiGUI();
        khuyenmaigui.setVisible(true);
            // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
    // TODO add your handling code here:
        this.dispose();
    
        // Mở cửa sổ mới
        KetCaGUI ketcagui = new KetCaGUI();
        ketcagui.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    
        // Mở cửa sổ mới
        MonAnGUI monangui = new MonAnGUI();
        monangui.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        List<Ban> listAll=banDAO.getall();
        //System.err.println(listAll);
        jPanel5.removeAll();
        paintBan(listAll);
        jPanel5.repaint();
        jPanel5.validate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        Ban_DAO b = new Ban_DAO();
        String chk = b.check();
        if (chk.equals("error")) 
            JOptionPane.showMessageDialog(this, "Vui lòng chọn bàn!!!");
        else{
            FormDoiBan formdoiban = new FormDoiBan(mahd);
            formdoiban.setVisible(true); 
        }

    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        Ban_DAO b = new Ban_DAO();
        String chk = b.check();
        if (chk.equals("error")) 
            JOptionPane.showMessageDialog(this, "Vui lòng chọn bàn!!!");
        else{
            FormTachDon formtachdon = new FormTachDon(mahd);
            formtachdon.setVisible(true);    
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        Ban_DAO b = new Ban_DAO();
        b.fillZero();
        jLabel5.setText("Bàn 0");
    }//GEN-LAST:event_jButton12ActionPerformed
    private void paintBan(List<Ban> list){
        int x=20;
        int y=20;
        
        for (Ban ban : list) {
            JButton jp = paint1Ban(ban);
            jPanel5.add(jp, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, 87, 87));
            jp.setBounds(x, y, 87, 87);
            x=x+117;
            if(x>672){
                x=20;
                y=y+97;
            }
            
            //jpp = new javax.swing.JPanel();
            jp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabel5.setText(ban.getten());
                jPanel6.repaint();
                jLabel13.setText("Khách Hàng");
                tongtienHD=0;
                Ban_DAO b = new Ban_DAO();
                b.fillZero();
                b.capNhapHoatDong(ban.getMaBan());
                jPanel6.removeAll();
                TrangChu_DAO ds = new TrangChu_DAO();
                List<HoaDon> list = ds.getall(ban.getMaBan());
                int count = 0;
                int z = 0;
                for (HoaDon s : list)
                { 
                    String tma = null;
                    int c = 0;
                    int sl = 0;
                    mahd = s.getMaHoaDon();
                    jLabel13.setText(s.getMaKH().getMaKH());
                    jLabel15.setText(s.getMaMonAn().size()+"");
                    for (MonAn ma : s.getMaMonAn()){
                        tma = ma.getMaMonAn();
                        sl = ma.getsl();
                        int km = ma.getGiaTien()*ma.getKhuyenMai();
                        c = ma.getGiaTien() - km/100;
                        //s.getMaMonAn().removeFirst();
                        count++;
                        JPanel jpp = paint1mon(count, tma, sl, c);
                        
                        // Code of sub-components and layout - not shown here
                        jPanel6.add(jpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10+z, 670, 90));
                        z += 90;
                    }
                    
                }
            }
        });
        }
                
    }
    private JPanel paint1mon(int count, String tma, int sl, int c){
        JPanel jpp = new JPanel();
        jpp.setBackground(new java.awt.Color(255, 255, 255));
        jpp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JButton bntxoa = new javax.swing.JButton();
        bntxoa.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\xoa.png"));
        jpp.add(bntxoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.JLabel lbid = new javax.swing.JLabel();
        lbid.setBackground(new java.awt.Color(255, 255, 255));
        lbid.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lbid.setForeground(new java.awt.Color(178, 28, 77));
        lbid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbid.setText(count+"");
        jpp.add(lbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 20, -1));

        javax.swing.JLabel lbten = new javax.swing.JLabel();
        lbten.setBackground(new java.awt.Color(255, 255, 255));
        lbten.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lbten.setForeground(new java.awt.Color(178, 28, 77));
        lbten.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);    
        lbten.setText(tma);
        jpp.add(lbten, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 160, -1));

        javax.swing.JLabel lbdg = new javax.swing.JLabel();
        lbdg.setBackground(new java.awt.Color(255, 255, 255));
        lbdg.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lbdg.setForeground(new java.awt.Color(178, 28, 77));
        lbdg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbdg.setText(c+"");
        jpp.add(lbdg, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 130, -1));

        javax.swing.JSpinner spin = new javax.swing.JSpinner();
        spin.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        spin.setValue(sl);
        jpp.add(spin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 50, 30));

        javax.swing.JLabel lbtien = new javax.swing.JLabel();
        lbtien.setBackground(new java.awt.Color(255, 255, 255));
        lbtien.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lbtien.setForeground(new java.awt.Color(178, 28, 77));
        lbtien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtien.setText(c*sl+"");
        tongtienHD += c*sl;
        jpp.add(lbtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 120, -1));
        jLabel12.setText(tongtienHD+"");
        javax.swing.JLabel lbic = new javax.swing.JLabel();
        lbic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbic.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\note.png"));
        lbic.setPreferredSize(new java.awt.Dimension(24, 24));
        jpp.add(lbic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        javax.swing.JTextField tfgc = new javax.swing.JTextField();
        tfgc.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        tfgc.setForeground(new java.awt.Color(178, 28, 77));
        tfgc.setText("Nhập ghi chú");
        tfgc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(178, 28, 77)));
        jpp.add(tfgc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 170, 30));
        return jpp;
    }
    // Vẽ cái bàn ở đây
    private JButton paint1Ban(Ban ban){
//      JPanel jp=new JPanel();
        JButton btn1=new JButton();
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText(ban.getten());
        btn1.setBorder(BorderFactory.createEmptyBorder());
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        
        if(ban.getTrangThai().equals("Trống")){
            btn1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\banbinhthuong.png"));
        }
        if(ban.getTrangThai().equals("Bận")){
            btn1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\bancokhach.png"));
        }
        if(ban.getTrangThai().equals("Tạm Ngưng ")){
            btn1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\img\\banngung.png"));
        }
        return btn1;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TrangChuGUI().setVisible(true);
//           }
//       });
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jP1;
}
